### ISSUE TITLE
node-red-contrib-persistent-global-context moduel not found

### ISSUE THREAD

**Issue by glendower** [sesenlik/node-red-contrib-persistent-global-context#1]
I have installed the node via the palette and it appears to be successful, no errors reported.

I then trid to import the example but received an error 'unknown node'.

I looked at the node in the palette and it says 'module_not_found'
 
![image](https://user-images.githubusercontent.com/53557300/236406202-6ff38af6-5926-4c66-a4a7-a6ad376adf8b.png)

**Comment by noeldodd** [comment]
I think it's the backslashes in the package.json and one in the GlobalContext.json string in the .js file. They can be swapped out for single forward slashes.

To test you can download the zip and edit / install it by hand:

The two lines in package.json become:

`"main": "src/persistent-global-context.js"`

and

`"persistent-global-context": "src/persistent-global-context.js"`


and in src/persistent-global-context.js:

`const path = RED.settings.userDir + '/GlobalContext.json';`

then in your .node-red folder, run `npm install <path_to_pkg>`, restart node-red, and it should show up just fine. And it DOES work! (thx!)

**Comment by sesenlik** [comment]
Fixed and published the node. Thank you for pointing out the cause of the error @noeldodd. 👍
